---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgsql
  labels:
    app: pgsql
spec:
  serviceName: "pgsql"
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: pgsql
          image: docker.io/library/postgres:17.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: pgsql-env
            - secretRef:
                name: pgsql-secrets
          volumeMounts:
            - name: todo-mydb
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: todo-mydb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
